apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ecommerce-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/denisdbell/ecommerceaks
  ref:
    branch: main
  secretRef:
    name: flux-system
