name: Build and Deploy Aks

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push images
      run: |
        az acr build --registry ecommerceacrdenis --image api-gateway:${{ github.sha }}          services/api-gateway
        az acr build --registry ecommerceacrdenis --image order-service:${{ github.sha }}        services/order-service
        az acr build --registry ecommerceacrdenis --image notification-service:${{ github.sha }} services/notification-service

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ecommerce-rg
        cluster-name: ecommerce-aks

    - name: Helm upgrade
      run: |
        helm upgrade api-gateway          helm/api-gateway          -n api-gateway          --set image.tag=${{ github.sha }}
        helm upgrade order-service        helm/order-service        -n order-service        --set image.tag=${{ github.sha }}
        helm upgrade notification-service helm/notification-service -n notification-service --set image.tag=${{ github.sha }}
