apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: api-gateway
  chart:
    spec:
      chart: ./helm/api-gateway
      sourceRef:
        kind: GitRepository
        name: ecommerce-platform
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecommerceacrdenis.azurecr.io/api-gateway
      tag: efcf9253574a5d30808ca47713c94103bfa75dc7
    replicaCount: 2
