apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notification-service
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: notification-service
  chart:
    spec:
      chart: ./helm/notification-service
      sourceRef:
        kind: GitRepository
        name: ecommerce-platform
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecommerceacrdenis.azurecr.io/notification-service
      tag: e300525c91007c9d3370eff594d2a96d1717c0d6
    replicaCount: 2
