apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notification-service
  namespace: flux-system
spec:
  interval: 5m
  releaseName: notification-service
  targetNamespace: notification-service
  chart:
    spec:
      chart: ./helm/notification-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecommerceacrdenis.azurecr.io/notification-service
      tag: 41070e500218a11b176d8598df66062f95cf5575
    replicaCount: 2
