apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: order-service
  chart:
    spec:
      chart: ./helm/order-service
      sourceRef:
        kind: GitRepository
        name: ecommerce-platform
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecommerceacrdenis.azurecr.io/order-service
      tag: 144ba73fc4527a763381f1a0007d617ca5f5430f
    replicaCount: 2
