apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: flux-system
spec:
  interval: 5m
  releaseName: order-service
  targetNamespace: order-service
  chart:
    spec:
      chart: ./helm/order-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecommerceacrdenis.azurecr.io/order-service
      tag: a1af5caee075015c515ea2e6109bc4c3bd699e3c
    replicaCount: 2
