replicaCount: 2

image:
  repository: ecommerceacrdenis.azurecr.io/order-service
  tag: latest
  pullPolicy: Always

namespace: order-service

service:
  type: ClusterIP
  port: 3001

workloadIdentity:
  clientId: "32facfef-c034-4678-9a8c-d6427d83fcd9"

keyVault:
  name: "ecommerce-kv-aks"
  tenantId: "8af2a7d4-d3a6-44ab-8818-f84ba51bd431"

env:
  NOTIFICATION_SERVICE_URL: "http://notification-service.notification-service.svc.cluster.local:3002"
