apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: api-gateway
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ecommerce-tls
  namespace: api-gateway
spec:
  secretName: ecommerce-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
  - api.20.81.30.78.nip.io
