apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-service-secrets
  namespace: order-service
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "32facfef-c034-4678-9a8c-d6427d83fcd9"
    keyvaultName: "ecommerce-kv"
    tenantId: "8af2a7d4-d3a6-44ab-8818-f84ba51bd431"
    objects: |
      array:
        - |
          objectName: postgres-password    # name of secret in Key Vault
          objectType: secret
        - |
          objectName: api-key
          objectType: secret