apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/gitrepository.yaml
  - ecommerce-kustomization.yaml
  - releases/api-gateway.yaml
  - releases/order-service.yaml
  - releases/notification-service.yaml
