apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ecommerce-kustomization.yaml
  - sources/ingress-nginx-helmrepo.yaml
  - releases/ingress-nginx.yaml
  - releases/api-gateway.yaml
  - releases/order-service.yaml
  - releases/notification-service.yaml
