name: Build and Deploy Aks

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push images
      run: |
        az acr build --registry ecommerceacrdenis --image api-gateway:${{ github.sha }}          services/api-gateway
        az acr build --registry ecommerceacrdenis --image order-service:${{ github.sha }}        services/order-service
        az acr build --registry ecommerceacrdenis --image notification-service:${{ github.sha }} services/notification-service

    - name: Update image tags for Flux
      run: |
        sed -i "s|tag: .*|tag: ${{ github.sha }}|g" flux/releases/api-gateway.yaml
        sed -i "s|tag: .*|tag: ${{ github.sha }}|g" flux/releases/order-service.yaml
        sed -i "s|tag: .*|tag: ${{ github.sha }}|g" flux/releases/notification-service.yaml

    - name: Commit updated image tags
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add flux/releases/
        git commit -m "chore: update image tags to ${{ github.sha }}"
        git push
